### ISSUE TITLE
EMA-Classic\Core\Team-Classic.lua:1876: attempt to concatenate local 'displayCharacterRleam' (a nil value)

### ISSUE THREAD

**Issue by mooreatv** [ebonyfaye/ema-classic#2]
I get this quite a lot:

```
24x EMA-Classic\Core\Team-Classic.lua:1876: attempt to concatenate local 'displayCharacterRleam' (a nil value)
EMA-Classic\Core\Team-Classic.lua:1876: in function `SettingsTeamListScrollRefresh'
EMA-Classic\Core\Team-Classic.lua:1776: in function `SettingsRefresh'
EMA-Classic\Core\Team-Classic.lua:1665: in function <EMA-Classic\Core\Team-Classic.lua:1659>
[C]: ?
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:498: in function `InitializeAddon'
DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:613: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
```

It could be because of how I call  `EMAApi.AddMember(fullname)` but not sure why it's sometimes/often but not always or why

**Comment by ebonyfaye** [comment]
So your using the API to add a member without a realm name? Even though it's in classic and realm mean nothing they still need them for some functions. ( And nerver know when blizzard will cross realm groups) so you need to add a realm name as it will not get automatically added like it does though the gui

**Comment by mooreatv** [comment]
Well I do send "fullname" ie Toon-Realm but somehow it fails sometime; I'll try to debug more when exactly/why
